{
 "title": "疫情实时动态",
 "tags": [ "疫情" ],
 "time": { "from": "2020-01-10T16:00:00.000Z", "to": "now" },
 "refresh": "2h",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>疫情实时动态</span>\n</div>",
   "targets": [
    { "project": "acs_ecs_dashboard", "type": "timeserie", "xcol": "timestamp" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 2 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>全国（含港澳台）</span>\n</div>",
   "targets": [
    { "project": "acs_ecs_dashboard", "type": "timeserie", "xcol": "timestamp" }
   ]
  },
  {
   "title": "全国疫情",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "target": "cn_chart_value", "type": "timeserie" },
    { "target": "cn_chart_susNum", "type": "timeserie" }
   ]
  },
  {
   "title": "全国治愈/死亡",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "target": "cn_chart_cureNum", "type": "timeserie" },
    { "target": "cn_chart_deathNum", "type": "timeserie" }
   ]
  },
  {
   "title": "确诊",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "gntotal", "type": "timeserie" }
   ]
  },
  {
   "title": "疑似",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "sustotal", "type": "timeserie" }
   ]
  },
  {
   "title": "治愈",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "curetotal", "type": "timeserie" }
   ]
  },
  {
   "title": "死亡",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "deathtotal", "type": "timeserie" }
   ]
  },
  {
   "title": "较昨日",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "addcon", "type": "timeserie" }
   ]
  },
  {
   "title": "较昨日",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 8 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "wjw_addsus", "type": "timeserie" }
   ]
  },
  {
   "title": "较昨日",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "addcure", "type": "timeserie" }
   ]
  },
  {
   "title": "较昨日",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "adddeath", "type": "timeserie" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "uttil times", "type": "timeserie" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 11 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>上海</span>\n</div>",
   "targets": [
    { "project": "acs_ecs_dashboard", "type": "timeserie", "xcol": "timestamp" }
   ]
  },
  {
   "title": "上海疫情",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "target": "sh_chart_value", "type": "timeserie" },
    { "target": "sh_chart_susNum", "type": "timeserie" }
   ]
  },
  {
   "title": "上海治愈/死亡",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "target": "sh_chart_cureNum", "type": "timeserie" },
    { "target": "sh_chart_deathNum", "type": "timeserie" }
   ]
  },
  {
   "title": "确诊",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "sh_value", "type": "timeserie" }
   ]
  },
  {
   "title": "疑似",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 13 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "sh_susNum", "type": "timeserie" }
   ]
  },
  {
   "title": "治愈",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 13 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "sh_cureNum", "type": "timeserie" }
   ]
  },
  {
   "title": "死亡",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 13 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "sh_deathNum", "type": "timeserie" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "target": "sh uttil times", "type": "timeserie" }
   ]
  },
  {
   "title": "中国病例",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "target": "all", "type": "table" }
   ]
  },
  {
   "title": "上海病例",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "target": "sh", "type": "table" }
   ]
  }
 ]
}