apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: feiyan-datasource
  name: feiyan-datasource
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: feiyan-datasource
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: feiyan-datasource
    spec:
      containers:
      - image: guoxudongdocker/feiyan-datasource
        imagePullPolicy: Always
        name: feiyan-datasource
        ports:
        - containerPort: 3000
          name: web
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: web
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
      imagePullSecrets:
      - name: registry-pull-secret

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: feiyan-datasource
  name: feiyan-datasource
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: web
  selector:
    app.kubernetes.io/name: feiyan-datasource
  sessionAffinity: None
  type: ClusterIP
